import { Errors, FS, Platform } from '@shared'
import { belongsToProject, nestedProjectRoots } from './ProjectSourceOwnership'
import type { ProjectToolingSourceMapping } from './ProjectTooling'

const MANIFEST_PATH = '.tao/typescript/outputs.json'
const SNAPSHOT_MARKER = '// Generated by Tao from a dependency source. Edit the original file instead.'
const CONTRACT_MARKER = '// Generated by Tao.'
const LEGACY_ADJACENT_CONTRACT_MARKER =
  '// Generated by Tao. Edit the .tao source or its handwritten TypeScript sidecar instead.'

export type ProjectPlannedOutput = {
  path: string
  sourcePath: string
  content: string
  kind: 'contract' | 'snapshot'
  sourceMappings: readonly ProjectToolingSourceMapping[]
}

type OwnedOutput = {
  path: string
  sourcePath: string
  hash: string
  kind: ProjectPlannedOutput['kind']
  sourceMappings: readonly ProjectToolingSourceMapping[]
}

type OutputManifest = { version: 1; outputs: OwnedOutput[] }

export type ProjectPublishedOutputs = {
  contractPaths: readonly string[]
  snapshotPaths: readonly string[]
  sourceMappings: readonly ProjectToolingSourceMapping[]
  changedOutputPaths: readonly string[]
}

/** Snapshot source without changing its imports or line coordinates. JSON cannot carry a comment. */
export function snapshotContent(sourcePath: string, original: string): string {
  return FS.extname(sourcePath) === '.json' ? original : `${SNAPSHOT_MARKER}\n${original}`
}

/** Remove contracts written beside Tao sources by the former publisher, under the project lock. */
export async function removeLegacyAdjacentContracts(root: string): Promise<string[]> {
  const projectRoot = FS.resolvePath(root)
  const nestedRoots = await nestedProjectRoots(projectRoot)
  const removed: string[] = []
  for await (
    const path of FS.walk(projectRoot, {
      extensions: ['.ts'],
      excludeDirectory: name => name === 'node_modules',
    })
  ) {
    if (
      !path.endsWith('.tao.ts')
      || !belongsToProject(path, projectRoot, nestedRoots)
      || await FS.isSymbolicLink(path)
    ) {
      continue
    }
    if ((await FS.readTextPrefix(path, LEGACY_ADJACENT_CONTRACT_MARKER.length)) !== LEGACY_ADJACENT_CONTRACT_MARKER) {
      continue
    }
    await FS.removeFileWithinBoundary(path, projectRoot)
    removed.push(path)
  }
  return removed
}

/** Read the manifest and publish exactly the owned output set. Must run under the project lock. */
export async function publishProjectOutputs(
  root: string,
  planned: readonly ProjectPlannedOutput[] | undefined,
): Promise<ProjectPublishedOutputs> {
  const projectRoot = FS.resolvePath(root)
  const generatedRoot = FS.resolvePath('.tao-ts', projectRoot)
  const manifestPath = FS.resolvePath(MANIFEST_PATH, projectRoot)
  const previous = await readManifest(manifestPath)
  const next = planned === undefined
    ? previous.outputs.filter(output => FS.existsSync(output.sourcePath))
    : planned.map(output => ownedOutput(output, generatedRoot))
  const previousByPath = new Map(previous.outputs.map(output => [output.path, output]))
  const nextByPath = new Map(next.map(output => [output.path, output]))
  if (nextByPath.size !== next.length) {
    return Errors.throwUnexpected('Expected: each generated project output has one owner.')
  }

  const changedOutputPaths: string[] = []
  if (planned !== undefined) {
    for (const output of planned) {
      const path = FS.resolvePath(output.path)
      assertGeneratedPath(path, generatedRoot)
      const prior = previousByPath.get(path)
      if (await FS.exists(path) && prior === undefined && !await hasGeneratedMarker(path)) {
        return Errors.throwUserInput(`Cannot publish Tao output over a handwritten file: ${path}.`)
      }
      const current = await FS.isFile(path) ? await FS.readText(path) : undefined
      if (current !== output.content) {
        await FS.mkdirWithinBoundary(FS.dirname(path), projectRoot)
        await FS.writeText(path, output.content)
        changedOutputPaths.push(path)
      }
    }
  }
  for (const output of previous.outputs) {
    if (nextByPath.has(output.path)) {
      continue
    }
    assertGeneratedPath(output.path, generatedRoot)
    if (await FS.isFile(output.path) && await outputStillOwned(output)) {
      await FS.removeFileWithinBoundary(output.path, projectRoot)
      changedOutputPaths.push(output.path)
    }
  }

  const manifest: OutputManifest = {
    version: 1,
    outputs: next.toSorted((left, right) => left.path.localeCompare(right.path)),
  }
  const content = `${JSON.stringify(manifest, null, 2)}\n`
  if (!await FS.isFile(manifestPath) || await FS.readText(manifestPath) !== content) {
    await FS.writeText(manifestPath, content)
    changedOutputPaths.push(manifestPath)
  }
  return {
    contractPaths: manifest.outputs.filter(output => output.kind === 'contract').map(output => output.path),
    snapshotPaths: manifest.outputs.filter(output => output.kind === 'snapshot').map(output => output.path),
    sourceMappings: manifest.outputs.flatMap(output => output.sourceMappings),
    changedOutputPaths,
  }
}

function ownedOutput(output: ProjectPlannedOutput, generatedRoot: string): OwnedOutput {
  const path = FS.resolvePath(output.path)
  assertGeneratedPath(path, generatedRoot)
  return {
    path,
    sourcePath: FS.resolvePath(output.sourcePath),
    hash: Platform.sha256Hex(output.content),
    kind: output.kind,
    sourceMappings: output.sourceMappings,
  }
}

function assertGeneratedPath(path: string, generatedRoot: string): void {
  if (!FS.pathIsWithin(path, generatedRoot) || path === generatedRoot) {
    Errors.throwUnexpected(`Expected: generated project output inside ${generatedRoot}; received ${path}.`)
  }
}

async function hasGeneratedMarker(path: string): Promise<boolean> {
  const content = await FS.readText(path)
  return content.startsWith(CONTRACT_MARKER) || content.startsWith(SNAPSHOT_MARKER)
}

async function outputStillOwned(output: OwnedOutput): Promise<boolean> {
  const content = await FS.readText(output.path)
  return content.startsWith(CONTRACT_MARKER)
    || content.startsWith(SNAPSHOT_MARKER)
    || (FS.extname(output.path) === '.json' && Platform.sha256Hex(content) === output.hash)
}

async function readManifest(path: string): Promise<OutputManifest> {
  if (!await FS.isFile(path)) {
    return { version: 1, outputs: [] }
  }
  const value = await FS.readJson<OutputManifest>(path)
  if (value.version !== 1 || !Array.isArray(value.outputs)) {
    return Errors.throwUnexpected(`Expected: a project output manifest at ${path}.`)
  }
  return value
}
