/******************************************************************************
 * This file was generated by langium-cli 4.2.1.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

/* eslint-disable */
import * as langium from 'langium';

export const TaoLangTerminals = {
    TS_CODE_BLOCK: /```ts(?:[\s\S]*?```)/,
    STRING: /"([^"\\]|\\.)*"/,
    ID: /[_a-zA-Z][\w_]*/,
    WS: /\s+/,
    ML_COMMENT: /\/\*[\s\S]*?\*\//,
    SL_COMMENT: /\/\/[^\n\r]*/,
};

export type TaoLangTerminalNames = keyof typeof TaoLangTerminals;

export type TaoLangKeywordNames =
    | ","
    | "app"
    | "inject"
    | "render"
    | "text"
    | "ui"
    | "{"
    | "}";

export type TaoLangTokenNames = TaoLangTerminalNames | TaoLangKeywordNames;

export interface AppDeclaration extends langium.AstNode {
    readonly $container: AppDeclaration | Block | TaoFile;
    readonly $type: 'AppDeclaration';
    name: string;
    statements: Array<Statement>;
}

export const AppDeclaration = {
    $type: 'AppDeclaration',
    name: 'name',
    statements: 'statements'
} as const;

export function isAppDeclaration(item: unknown): item is AppDeclaration {
    return reflection.isInstance(item, AppDeclaration.$type);
}

export type AppGrammarEntrypoint = AppDeclaration;

export const AppGrammarEntrypoint = {
    $type: 'AppGrammarEntrypoint'
} as const;

export function isAppGrammarEntrypoint(item: unknown): item is AppGrammarEntrypoint {
    return reflection.isInstance(item, AppGrammarEntrypoint.$type);
}

export type AppStatement = AppUi;

export const AppStatement = {
    $type: 'AppStatement'
} as const;

export function isAppStatement(item: unknown): item is AppStatement {
    return reflection.isInstance(item, AppStatement.$type);
}

export interface AppUi extends langium.AstNode {
    readonly $container: AppDeclaration | Block | TaoFile;
    readonly $type: 'AppUi';
    ui: langium.Reference<ViewDeclaration>;
}

export const AppUi = {
    $type: 'AppUi',
    ui: 'ui'
} as const;

export function isAppUi(item: unknown): item is AppUi {
    return reflection.isInstance(item, AppUi.$type);
}

export interface Argument extends langium.AstNode {
    readonly $container: ArgumentList;
    readonly $type: 'Argument';
    value: StringLiteral;
}

export const Argument = {
    $type: 'Argument',
    value: 'value'
} as const;

export function isArgument(item: unknown): item is Argument {
    return reflection.isInstance(item, Argument.$type);
}

export interface ArgumentList extends langium.AstNode {
    readonly $container: Render;
    readonly $type: 'ArgumentList';
    arguments: Array<Argument>;
}

export const ArgumentList = {
    $type: 'ArgumentList',
    arguments: 'arguments'
} as const;

export function isArgumentList(item: unknown): item is ArgumentList {
    return reflection.isInstance(item, ArgumentList.$type);
}

export interface Block extends langium.AstNode {
    readonly $container: Render | ViewDeclaration;
    readonly $type: 'Block';
    statements: Array<Statement>;
}

export const Block = {
    $type: 'Block',
    statements: 'statements'
} as const;

export function isBlock(item: unknown): item is Block {
    return reflection.isInstance(item, Block.$type);
}

export type BlocksGrammarEntrypoint = Block;

export const BlocksGrammarEntrypoint = {
    $type: 'BlocksGrammarEntrypoint'
} as const;

export function isBlocksGrammarEntrypoint(item: unknown): item is BlocksGrammarEntrypoint {
    return reflection.isInstance(item, BlocksGrammarEntrypoint.$type);
}

export type Declaration = AppDeclaration | ViewDeclaration;

export const Declaration = {
    $type: 'Declaration'
} as const;

export function isDeclaration(item: unknown): item is Declaration {
    return reflection.isInstance(item, Declaration.$type);
}

export type ExpressionsGrammarEntrypoint = ArgumentList;

export const ExpressionsGrammarEntrypoint = {
    $type: 'ExpressionsGrammarEntrypoint'
} as const;

export function isExpressionsGrammarEntrypoint(item: unknown): item is ExpressionsGrammarEntrypoint {
    return reflection.isInstance(item, ExpressionsGrammarEntrypoint.$type);
}

export interface Injection extends langium.AstNode {
    readonly $container: AppDeclaration | Block | Render | TaoFile;
    readonly $type: 'Injection';
    tsCodeBlock: string;
}

export const Injection = {
    $type: 'Injection',
    tsCodeBlock: 'tsCodeBlock'
} as const;

export function isInjection(item: unknown): item is Injection {
    return reflection.isInstance(item, Injection.$type);
}

export interface ParameterDeclaration extends langium.AstNode {
    readonly $container: ParameterList;
    readonly $type: 'ParameterDeclaration';
    name: string;
    type: PrimitiveType;
}

export const ParameterDeclaration = {
    $type: 'ParameterDeclaration',
    name: 'name',
    type: 'type'
} as const;

export function isParameterDeclaration(item: unknown): item is ParameterDeclaration {
    return reflection.isInstance(item, ParameterDeclaration.$type);
}

export interface ParameterList extends langium.AstNode {
    readonly $container: ViewDeclaration;
    readonly $type: 'ParameterList';
    parameters: Array<ParameterDeclaration>;
}

export const ParameterList = {
    $type: 'ParameterList',
    parameters: 'parameters'
} as const;

export function isParameterList(item: unknown): item is ParameterList {
    return reflection.isInstance(item, ParameterList.$type);
}

export type PrimitiveType = 'text';

export function isPrimitiveType(item: unknown): item is PrimitiveType {
    return item === 'text';
}

export interface Render extends langium.AstNode {
    readonly $container: AppDeclaration | Block | TaoFile;
    readonly $type: 'Render';
    argumentList?: ArgumentList;
    block?: Block;
    injection?: Injection;
    view?: langium.Reference<ViewDeclaration>;
}

export const Render = {
    $type: 'Render',
    argumentList: 'argumentList',
    block: 'block',
    injection: 'injection',
    view: 'view'
} as const;

export function isRender(item: unknown): item is Render {
    return reflection.isInstance(item, Render.$type);
}

export type Statement = AppUi | Declaration | Injection | Render;

export const Statement = {
    $type: 'Statement'
} as const;

export function isStatement(item: unknown): item is Statement {
    return reflection.isInstance(item, Statement.$type);
}

export interface StringLiteral extends langium.AstNode {
    readonly $container: Argument;
    readonly $type: 'StringLiteral';
    value: string;
}

export const StringLiteral = {
    $type: 'StringLiteral',
    value: 'value'
} as const;

export function isStringLiteral(item: unknown): item is StringLiteral {
    return reflection.isInstance(item, StringLiteral.$type);
}

export interface TaoFile extends langium.AstNode {
    readonly $type: 'TaoFile';
    statements: Array<Statement>;
}

export const TaoFile = {
    $type: 'TaoFile',
    statements: 'statements'
} as const;

export function isTaoFile(item: unknown): item is TaoFile {
    return reflection.isInstance(item, TaoFile.$type);
}

export interface TerminalsGrammarEntrypoint extends langium.AstNode {
    readonly $type: 'TerminalsGrammarEntrypoint';
    value: string;
}

export const TerminalsGrammarEntrypoint = {
    $type: 'TerminalsGrammarEntrypoint',
    value: 'value'
} as const;

export function isTerminalsGrammarEntrypoint(item: unknown): item is TerminalsGrammarEntrypoint {
    return reflection.isInstance(item, TerminalsGrammarEntrypoint.$type);
}

export type TopLevelStatement = Declaration;

export const TopLevelStatement = {
    $type: 'TopLevelStatement'
} as const;

export function isTopLevelStatement(item: unknown): item is TopLevelStatement {
    return reflection.isInstance(item, TopLevelStatement.$type);
}

export interface ViewDeclaration extends langium.AstNode {
    readonly $container: AppDeclaration | Block | TaoFile;
    readonly $type: 'ViewDeclaration';
    block: Block;
    name: string;
    parameterList?: ParameterList;
}

export const ViewDeclaration = {
    $type: 'ViewDeclaration',
    block: 'block',
    name: 'name',
    parameterList: 'parameterList'
} as const;

export function isViewDeclaration(item: unknown): item is ViewDeclaration {
    return reflection.isInstance(item, ViewDeclaration.$type);
}

export type ViewsGrammarEntrypoint = ViewDeclaration;

export const ViewsGrammarEntrypoint = {
    $type: 'ViewsGrammarEntrypoint'
} as const;

export function isViewsGrammarEntrypoint(item: unknown): item is ViewsGrammarEntrypoint {
    return reflection.isInstance(item, ViewsGrammarEntrypoint.$type);
}

export type ViewStatement = Render;

export const ViewStatement = {
    $type: 'ViewStatement'
} as const;

export function isViewStatement(item: unknown): item is ViewStatement {
    return reflection.isInstance(item, ViewStatement.$type);
}

export type TaoLangAstType = {
    AppDeclaration: AppDeclaration
    AppGrammarEntrypoint: AppGrammarEntrypoint
    AppStatement: AppStatement
    AppUi: AppUi
    Argument: Argument
    ArgumentList: ArgumentList
    Block: Block
    BlocksGrammarEntrypoint: BlocksGrammarEntrypoint
    Declaration: Declaration
    ExpressionsGrammarEntrypoint: ExpressionsGrammarEntrypoint
    Injection: Injection
    ParameterDeclaration: ParameterDeclaration
    ParameterList: ParameterList
    Render: Render
    Statement: Statement
    StringLiteral: StringLiteral
    TaoFile: TaoFile
    TerminalsGrammarEntrypoint: TerminalsGrammarEntrypoint
    TopLevelStatement: TopLevelStatement
    ViewDeclaration: ViewDeclaration
    ViewStatement: ViewStatement
    ViewsGrammarEntrypoint: ViewsGrammarEntrypoint
}

export class TaoLangAstReflection extends langium.AbstractAstReflection {
    override readonly types = {
        AppDeclaration: {
            name: AppDeclaration.$type,
            properties: {
                name: {
                    name: AppDeclaration.name
                },
                statements: {
                    name: AppDeclaration.statements,
                    defaultValue: []
                }
            },
            superTypes: [AppGrammarEntrypoint.$type, Declaration.$type]
        },
        AppGrammarEntrypoint: {
            name: AppGrammarEntrypoint.$type,
            properties: {
            },
            superTypes: []
        },
        AppStatement: {
            name: AppStatement.$type,
            properties: {
            },
            superTypes: []
        },
        AppUi: {
            name: AppUi.$type,
            properties: {
                ui: {
                    name: AppUi.ui,
                    referenceType: ViewDeclaration.$type
                }
            },
            superTypes: [AppStatement.$type, Statement.$type]
        },
        Argument: {
            name: Argument.$type,
            properties: {
                value: {
                    name: Argument.value
                }
            },
            superTypes: []
        },
        ArgumentList: {
            name: ArgumentList.$type,
            properties: {
                arguments: {
                    name: ArgumentList.arguments,
                    defaultValue: []
                }
            },
            superTypes: [ExpressionsGrammarEntrypoint.$type]
        },
        Block: {
            name: Block.$type,
            properties: {
                statements: {
                    name: Block.statements,
                    defaultValue: []
                }
            },
            superTypes: [BlocksGrammarEntrypoint.$type]
        },
        BlocksGrammarEntrypoint: {
            name: BlocksGrammarEntrypoint.$type,
            properties: {
            },
            superTypes: []
        },
        Declaration: {
            name: Declaration.$type,
            properties: {
            },
            superTypes: [Statement.$type, TopLevelStatement.$type]
        },
        ExpressionsGrammarEntrypoint: {
            name: ExpressionsGrammarEntrypoint.$type,
            properties: {
            },
            superTypes: []
        },
        Injection: {
            name: Injection.$type,
            properties: {
                tsCodeBlock: {
                    name: Injection.tsCodeBlock
                }
            },
            superTypes: [Statement.$type]
        },
        ParameterDeclaration: {
            name: ParameterDeclaration.$type,
            properties: {
                name: {
                    name: ParameterDeclaration.name
                },
                type: {
                    name: ParameterDeclaration.type
                }
            },
            superTypes: []
        },
        ParameterList: {
            name: ParameterList.$type,
            properties: {
                parameters: {
                    name: ParameterList.parameters,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        Render: {
            name: Render.$type,
            properties: {
                argumentList: {
                    name: Render.argumentList
                },
                block: {
                    name: Render.block
                },
                injection: {
                    name: Render.injection
                },
                view: {
                    name: Render.view,
                    referenceType: ViewDeclaration.$type
                }
            },
            superTypes: [Statement.$type, ViewStatement.$type]
        },
        Statement: {
            name: Statement.$type,
            properties: {
            },
            superTypes: []
        },
        StringLiteral: {
            name: StringLiteral.$type,
            properties: {
                value: {
                    name: StringLiteral.value
                }
            },
            superTypes: []
        },
        TaoFile: {
            name: TaoFile.$type,
            properties: {
                statements: {
                    name: TaoFile.statements,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        TerminalsGrammarEntrypoint: {
            name: TerminalsGrammarEntrypoint.$type,
            properties: {
                value: {
                    name: TerminalsGrammarEntrypoint.value
                }
            },
            superTypes: []
        },
        TopLevelStatement: {
            name: TopLevelStatement.$type,
            properties: {
            },
            superTypes: []
        },
        ViewDeclaration: {
            name: ViewDeclaration.$type,
            properties: {
                block: {
                    name: ViewDeclaration.block
                },
                name: {
                    name: ViewDeclaration.name
                },
                parameterList: {
                    name: ViewDeclaration.parameterList
                }
            },
            superTypes: [Declaration.$type, ViewsGrammarEntrypoint.$type]
        },
        ViewStatement: {
            name: ViewStatement.$type,
            properties: {
            },
            superTypes: []
        },
        ViewsGrammarEntrypoint: {
            name: ViewsGrammarEntrypoint.$type,
            properties: {
            },
            superTypes: []
        }
    } as const satisfies langium.AstMetaData
}

export const reflection = new TaoLangAstReflection();
