/******************************************************************************
 * This file was generated by langium-cli 4.2.1.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

import type { LangiumSharedCoreServices, LangiumCoreServices, LangiumGeneratedCoreServices, LangiumGeneratedSharedCoreServices, LanguageMetaData, Module } from 'langium';
import { TaoLangAstReflection } from './ast.js';
import { TaoLangGrammar } from './grammar.js';

export const TaoLangLanguageMetaData = {
    languageId: 'tao-lang',
    fileExtensions: ['.tao'],
    caseInsensitive: false,
    mode: 'development'
} as const satisfies LanguageMetaData;

export const TaoLangGeneratedSharedModule: Module<LangiumSharedCoreServices, LangiumGeneratedSharedCoreServices> = {
    AstReflection: () => new TaoLangAstReflection()
};

export const TaoLangGeneratedModule: Module<LangiumCoreServices, LangiumGeneratedCoreServices> = {
    Grammar: () => TaoLangGrammar(),
    LanguageMetaData: () => TaoLangLanguageMetaData,
    parser: {}
};
