import { ASTUtils, Type } from '@ast-utils'
import { AST, Langium, type ModuleOrigin, type ParsedFile } from '@parser'
import { Assert, type DiagnosticRange, FS, Platform, Switch, TaoResources } from '@shared'
import { authLibraryExport } from './codegen/react-native/app/auth-context'
import {
  ConfigurationCompiler,
  isRuntimeConfigurableDeclaration,
} from './codegen/react-native/app/ConfigurationCompiler'

type BridgeContract = {
  arity?: string
  exportName: string
  path: string
  result?: string
  sourceRange?: DiagnosticRange
  type: string
}

export type BridgeSourceMapping = { generated: DiagnosticRange; source: DiagnosticRange }
export type BridgeModule = {
  path: string
  code: string
  sourcePath: string
  sourceMappings: readonly BridgeSourceMapping[]
  implementationPaths: readonly { sourcePath: string; path: string }[]
}

export const bridgeGeneratedMarker =
  '// Generated by Tao. Edit the .tao source or its handwritten TypeScript sidecar instead.'

/** BridgeMetadata is the TypeScript-facing contract generated beside each Tao boundary source. */
export const BridgeMetadata = {
  resultType: typescriptType,
  /** Source sidecar roots referenced by a reachable declaration closure, without sibling declarations. */
  implementationSidecarRoots(declarations: readonly AST.Declaration[]): readonly string[] {
    const roots = new Set<string>()
    const add = (node: AST.Node, path: string): void => {
      roots.add(FS.resolvePath(path, FS.dirname(AST.getDocument(node).uri.path)))
    }
    for (const declaration of declarations) {
      for (const node of [declaration, ...AST.streamAllContents(declaration)]) {
        if (AST.isFromExpression(node)) {
          add(node, node.path)
        } else if (AST.isActionDeclaration(node) && node.foreign !== undefined) {
          add(node, node.foreign.path)
        } else if (AST.isViewDeclaration(node) && node.foreign !== undefined) {
          add(node, node.foreign.path)
        }
      }
      if (AST.isConfigurableDeclaration(declaration)) {
        const implementation = directConfigurationImplementation(declaration)
        if (implementation !== undefined) {
          add(implementation, implementation.path)
        }
      }
    }
    return [...roots]
  },
  /** typesFor mirrors the exported contract types in compiled Tao modules for copied sidecars. */
  typesFor(file: AST.TaoFile, statements: readonly AST.Statement[] = file.statements): string {
    const contracts = contractsOf(file, statements)
    return contracts.map((contract, index) => `export type ${contractTypeName(contracts, index)} = ${contract.type}`)
      .join('\n')
  },

  /** Case identities remain available to TypeScript type queries without selecting runtime work. */
  caseSetTypesFor(statements: readonly AST.Statement[]): string {
    return statements.filter(AST.isTypeDeclaration).filter(declaration => AST.isCaseSetTypeExpression(declaration.type))
      .map(caseSetTypeDeclaration).join('\n')
  },

  /** collect plans contracts without writing files; the project service owns publication. */
  collect(
    files: readonly ParsedFile[],
    projectRoot: string,
    origins: ReadonlyMap<string, ModuleOrigin> = new Map(),
    options: {
      runtimeRoot?: string
      selectedStatementsBySourcePath?: ReadonlyMap<string, readonly AST.Statement[]>
    } = {},
  ): BridgeModule[] {
    return files.flatMap(file => {
      const statements = options.selectedStatementsBySourcePath?.get(file.path) ?? file.ast.statements
      const contracts = contractsOf(file.ast, statements)
      if (
        contracts.length === 0
        && !file.ast.statements.some(isRuntimeConfigurableDeclaration)
        && !file.ast.statements.some(statement =>
          AST.isTypeDeclaration(statement) && AST.isCaseSetTypeExpression(statement.type)
        )
      ) {
        return []
      }
      const origin = origins.get(file.path)
      const path = bridgeOutputPath(projectRoot, file.path, origin)
      const implementationPaths = [...new Set(contracts.map(contract => contract.path))].map(contractPath => {
        const sourcePath = FS.resolvePath(contractPath, FS.dirname(file.path))
        return {
          sourcePath,
          path: isForeignOrigin(origin, projectRoot)
            ? dependencySnapshotPath(projectRoot, sourcePath, origin)
            : sourcePath,
        }
      })
      return [{
        path,
        ...moduleFor(
          contracts,
          file.ast.statements,
          path,
          file.path,
          implementationPaths,
          options.runtimeRoot,
        ),
        sourcePath: file.path,
        implementationPaths,
      }]
    })
  },
  dependencyNamespace,
  dependencySnapshotPath,
} as const

function bridgeOutputPath(projectRoot: string, sourcePath: string, origin?: ModuleOrigin): string {
  if (isForeignOrigin(origin, projectRoot)) {
    return `${dependencySnapshotPath(projectRoot, sourcePath, origin)}.ts`
  }
  if (FS.pathIsWithin(sourcePath, projectRoot)) {
    return FS.resolvePath(`.tao-ts/${FS.relativePath(projectRoot, sourcePath)}.ts`, projectRoot)
  }
  return `${
    dependencySnapshotPath(
      projectRoot,
      sourcePath,
      origin ?? {
        projectRoot: FS.dirname(sourcePath),
        modulePath: FS.dirname(sourcePath),
      },
    )
  }.ts`
}

function isForeignOrigin(origin: ModuleOrigin | undefined, projectRoot: string): origin is ModuleOrigin {
  return origin !== undefined && FS.resolvePath(origin.projectRoot) !== FS.resolvePath(projectRoot)
}

/** Place every file from one selected dependency origin in a private requester-owned snapshot. */
function dependencySnapshotPath(projectRoot: string, sourcePath: string, origin: ModuleOrigin): string {
  const relative = FS.relativePath(origin.projectRoot, sourcePath)
  Assert(!relative.startsWith('..'), 'dependency origin contains its source', { origin, sourcePath })
  return FS.resolvePath(`.tao-ts/.dependencies/${dependencyNamespace(origin.projectRoot)}/${relative}`, projectRoot)
}

/** One physical dependency project has one private source and npm-resolution environment. */
function dependencyNamespace(originProjectRoot: string): string {
  return Platform.sha256Hex(FS.resolvePath(originProjectRoot))
}

function contractsOf(file: AST.TaoFile, statements: readonly AST.Statement[] = file.statements): BridgeContract[] {
  const contracts: BridgeContract[] = []
  const nodes = statements.flatMap(statement => [statement, ...AST.streamAllContents(statement)])
  for (const bridge of nodes.filter(AST.isFromExpression)) {
    const expression = bridge.expression
    const exportName = AST.isFunctionCallExpression(expression)
      ? expression.function.$refText
      : AST.isValueReference(expression)
      ? expression.target.$refText
      : undefined
    if (exportName === undefined) {
      continue
    }
    const contextual = AST.getDocument(bridge).uri.path.endsWith('/@tao/auth/Auth.tao')
    if (contextual && exportName === 'Session') {
      contracts.push({
        exportName,
        path: bridge.path,
        sourceRange: bridgeOwnerRange(bridge),
        arity: '2',
        result: 'TR.Evaluable',
        type: '(scope: TR.AuthScope, cases: Readonly<Record<string, TR.Evaluable>>) => TR.Evaluable',
      })
      continue
    }
    const result = bridgedResultType(bridge)
    if (result === undefined) {
      continue
    }
    const type = AST.isFunctionCallExpression(expression)
      ? `(${contextual ? 'scope: TR.AuthScope, ' : ''}${
        expression.argumentList?.arguments.map((argument, index) =>
          `arg${index}: ${foreignActionParameterType(Type.ofArgument(argument))}`
        ).join(', ') ?? ''
      }) => ${typescriptType(result)}`
      : result.kind === 'primitive' && result.primitive === 'action'
      ? `(${
        result.parameters.map((parameter, index) =>
          `arg${index}${parameter.optional ? '?' : ''}: ${foreignActionParameterType(parameter.type)}`
        ).join(', ')
      }) => void | Promise<void>`
      : typescriptType(result)
    const actionValue = result.kind === 'primitive' && result.primitive === 'action'
    contracts.push({
      ...(AST.isFunctionCallExpression(expression)
        ? { arity: String((expression.argumentList?.arguments.length ?? 0) + (contextual ? 1 : 0)) }
        : actionValue
        ? { arity: String(result.parameters.length), result: 'void | Promise<void>' }
        : {}),
      exportName,
      path: bridge.path,
      sourceRange: bridgeOwnerRange(bridge),
      type,
    })
  }
  for (const action of nodes.filter(AST.isActionDeclaration)) {
    if (action.foreign === undefined) {
      continue
    }
    if (authLibraryExport(action)) {
      contracts.push({
        arity: '1',
        exportName: action.name,
        path: action.foreign.path,
        sourceRange: action.$cstNode?.range,
        result: 'TR.Action<[]>',
        type: '(scope: TR.AuthScope) => TR.Action<[]>',
      })
      continue
    }
    // The compiler fills Tao defaults before invoking the handwritten implementation.
    const parameters = AST.parametersOf(action).map((parameter, index) =>
      `arg${index}: ${foreignActionParameterType(Type.ofParameter(parameter))}`
    )
    const result = action.returnType ? typescriptType(Type.ofActionResult(action)) : 'void'
    contracts.push({
      arity: String(parameters.length),
      exportName: action.name,
      path: action.foreign.path,
      sourceRange: action.$cstNode?.range,
      result: `${result} | Promise<${result}>`,
      type: `(${parameters.join(', ')}) => ${result} | Promise<${result}>`,
    })
  }
  for (const view of nodes.filter(AST.isViewDeclaration)) {
    const foreign = view.foreign
    if (foreign === undefined) {
      continue
    }
    // Tao fills defaults before passing props to the handwritten component.
    const parameters = AST.parametersOf(view).map(parameter => {
      const value = viewParameterType(Type.ofParameter(parameter))
      return `${JSON.stringify(Type.parameterName(parameter))}: ${
        parameter.mutable
          ? `{ value: ${value}; change: (next: ${value}) => void | Promise<void> }`
          : value
      }`
    })
    const slots = foreign.slots.length === 0
      ? []
      : [`Slots: { ${foreign.slots.map(slot => `${JSON.stringify(slot.name)}: any`).join('; ')} }`]
    const children = foreign.content === 'content' ? ['children?: any'] : []
    const authProps = authLibraryExport(view)
      ? ['Auth?: TR.AuthScope', ...(view.name === 'AccountView' ? ['Account?: TR.Evaluable'] : [])]
      : []
    const props = [...parameters, ...authProps, 'Layout: any', 'Tag: any', ...slots, ...children]
    contracts.push({
      exportName: view.name,
      path: foreign.path,
      sourceRange: view.$cstNode?.range,
      type: `(props: { ${props.join('; ')} }) => ReturnType<typeof TR.VisualNativeRoot>`,
    })
  }
  for (const declaration of statements.filter(AST.isConfigurableDeclaration)) {
    const primitive = AST.configurationPrimitiveOf(declaration)
    if (primitive !== 'nav' && primitive !== 'datasource' && primitive !== 'auth') {
      continue
    }
    const implementation = directConfigurationImplementation(declaration)
    if (implementation === undefined) {
      continue
    }
    contracts.push({
      arity: '0',
      exportName: implementation.exportName,
      path: implementation.path,
      sourceRange: declaration.$cstNode?.range,
      type: `() => ${
        primitive === 'nav' ? 'TR.NavKind' : primitive === 'auth' ? 'TR.AuthProvider' : 'TR.DataProvider'
      }`,
    })
  }
  return contracts
}

function directConfigurationImplementation(
  declaration: AST.ConfigurableDeclaration,
): AST.ConfigurationImplementation | undefined {
  if (declaration.aliasTarget !== undefined) {
    return undefined
  }
  const implementation = AST.configurationImplementationOf(declaration)
  let owner: AST.Node | undefined = implementation
  while (owner !== undefined && owner !== declaration) {
    owner = owner.$container
  }
  return owner === declaration && implementation?.path !== undefined ? implementation : undefined
}

function bridgeOwnerRange(bridge: AST.FromExpression): DiagnosticRange | undefined {
  const owner = bridge.$container
  if (AST.isReturnStatement(owner)) {
    return AST.findOwningFunction(owner)?.$cstNode?.range ?? bridge.$cstNode?.range
  }
  return owner?.$cstNode?.range ?? bridge.$cstNode?.range
}

function bridgedResultType(bridge: AST.FromExpression): ASTUtils.TaoType | undefined {
  const owner = bridge.$container
  if (AST.isReturnStatement(owner)) {
    const functionOwner = AST.findOwningFunction(owner)
    return functionOwner?.returnType === undefined ? undefined : Type.ofFunctionReturn(functionOwner)
  }
  if (AST.isAliasDeclaration(owner)) {
    return owner.type === undefined ? undefined : Type.ofReference(owner.type)
  }
  if (AST.isTypeProperty(owner)) {
    return owner.type === undefined ? undefined : Type.ofReference(owner.type)
  }
  return undefined
}

function typescriptType(type: ASTUtils.TaoType, seen = new Set<AST.EntityDataDeclaration>()): string {
  return Switch.kind(type, {
    primitive: type => {
      if (type.primitive === 'action') {
        return runtimeActionType(type)
      }
      if (type.primitive === 'text' || type.primitive === 'color' || type.primitive === 'shortcut') {
        return 'string'
      }
      if (type.primitive === 'number' || type.primitive === 'time' || type.primitive === 'duration') {
        return 'number'
      }
      if (type.primitive === 'boolean') {
        return 'boolean'
      }
      if (type.primitive === 'none') {
        return 'null'
      }
      return 'unknown'
    },
    list: type => `Array<${typescriptType(type.element ?? { kind: 'unresolved' }, seen)}>`,
    union: type => type.members.map(member => typescriptType(member, seen)).join(' | '),
    entity: type => {
      if (seen.has(type.entity)) {
        return 'unknown'
      }
      seen.add(type.entity)
      const fields = Type.dataFields(type.entity).map(field =>
        `${JSON.stringify(field.name)}${field.optional ? '?' : ''}: ${typescriptType(Type.dataFieldType(field), seen)}`
      )
      seen.delete(type.entity)
      return `{ ${fields.join('; ')} }`
    },
    item: type => {
      const fields = (type.item ? Type.itemFields(type.item) : []).map(field => {
        const required = Type.itemFieldRequiresValue(field)
        const fieldType = Type.itemFieldType(field)
        const outputType = fieldType.kind === 'primitive' && fieldType.primitive === 'action'
          ? itemActionType(fieldType)
          : typescriptType(fieldType, seen)
        return `${JSON.stringify(field.name)}${required ? '' : '?'}: ${outputType}${required ? '' : ' | null'}`
      })
      return `{ ${fields.join('; ')} }`
    },
    enum: () => 'any',
    unresolved: () => 'unknown',
  })
}

/** View action parameters retain the runtime's invokable action and reactive argument wrappers. */
function viewParameterType(type: ASTUtils.TaoType): string {
  if (type.kind === 'primitive' && type.primitive === 'action') {
    return runtimeActionType(type)
  }
  return typescriptType(type)
}

function foreignActionParameterType(type: ASTUtils.TaoType): string {
  return type.kind === 'primitive' && type.primitive === 'action' ? runtimeActionType(type) : typescriptType(type)
}

function runtimeActionType(type: Extract<ASTUtils.TaoType, { kind: 'primitive'; primitive: 'action' }>): string {
  const parameters = type.parameters.map(parameter =>
    `${runtimeActionArgumentType(parameter.type)}${parameter.optional ? '?' : ''}`
  )
  return `TR.ActionValue<[${parameters.join(', ')}]>`
}

function runtimeActionArgumentType(type: ASTUtils.TaoType): string {
  if (type.kind === 'primitive' && type.primitive === 'action') {
    return `TR.Action<[${
      type.parameters.map(parameter => `${runtimeActionArgumentType(parameter.type)}${parameter.optional ? '?' : ''}`)
        .join(', ')
    }]>`
  }
  return type.kind === 'union' ? 'TR.Evaluable' : `TR.Value<${typescriptType(type)}>`
}

function itemActionType(type: Extract<ASTUtils.TaoType, { kind: 'primitive'; primitive: 'action' }>): string {
  return `{ invoke(...args: [${
    type.parameters.map(parameter => `TR.Value<${typescriptType(parameter.type)}>`).join(', ')
  }]): void | Promise<void> }`
}

/**
 * runtimeTypeImport names `TR` by a path from the generated module. The module is often opened
 * outside the project that maps `@tao/runtime`, so a package specifier does not resolve there.
 */
function runtimeTypeImport(modulePath: string, runtimeRoot?: string): string {
  const runtime = runtimeRoot === undefined
    ? TaoResources.resolve(`${TaoResources.RUNTIME_DIRECTORY}/TaoRuntime-src/TR.ts`)
      ?? FS.resolvePath('../../apps/runtime/TaoRuntime-src/TR.ts', import.meta.dirname)
    : FS.resolvePath('TaoRuntime-src/TR.ts', runtimeRoot)
  const relative = FS.relativePath(FS.dirname(FS.resolvePath(modulePath)), runtime).replace(/\.ts$/, '')
  const specifier = relative.startsWith('.') ? relative : `./${relative}`
  return `import type TR from ${JSON.stringify(specifier)}`
}

function moduleFor(
  contracts: readonly BridgeContract[],
  typeStatements: readonly AST.Statement[],
  modulePath: string,
  sourcePath: string,
  implementationPaths: readonly { sourcePath: string; path: string }[],
  runtimeRoot?: string,
): { code: string; sourceMappings: readonly BridgeSourceMapping[] } {
  const imports = new Map<string, string>()
  const lines = [bridgeGeneratedMarker, '']
  const sourceMappings: BridgeSourceMapping[] = []
  const sourceComment = (range: DiagnosticRange | undefined): void => {
    if (range === undefined) {
      return
    }
    const relative = FS.relativePath(FS.dirname(modulePath), sourcePath)
    lines.push(`// Source: ${relative}:${range.start.line + 1}:${range.start.character + 1}`)
  }
  const mapLine = (range: DiagnosticRange | undefined): void => {
    if (range === undefined) {
      return
    }
    const line = lines.length - 1
    const content = lines[line] ?? ''
    sourceMappings.push({
      generated: { start: { line, character: 0 }, end: { line, character: content.length } },
      source: range,
    })
  }
  const configurationTypes = typeStatements.filter(isRuntimeConfigurableDeclaration)
    .map(declaration => ({ code: sourceConfigurationType(declaration), sourceRange: declaration.$cstNode?.range }))
  const caseSets = typeStatements.filter(AST.isTypeDeclaration).filter(declaration =>
    AST.isCaseSetTypeExpression(declaration.type)
  )
  if (
    contracts.some(contract => contract.type.includes('TR.'))
    || caseSets.length > 0
    || contracts.some(contract => contract.type.includes('TR.NavKind') || contract.type.includes('TR.DataProvider'))
    || contracts.some(contract => contract.type.includes('TR.VisualNativeRoot'))
    || configurationTypes.some(type => type.code.includes('TR.'))
  ) {
    lines.push(runtimeTypeImport(modulePath, runtimeRoot))
  }
  for (const contract of contracts) {
    if (!imports.has(contract.path)) {
      imports.set(contract.path, `Sidecar${imports.size + 1}`)
    }
  }
  if (imports.size === 1) {
    const onlyPath = [...imports.keys()][0]
    Assert.defined(onlyPath, 'single bridge sidecar has one path')
    imports.set(onlyPath, 'Sidecar')
  }
  for (const [path, name] of imports) {
    const sidecar = FS.resolvePath(path, FS.dirname(sourcePath))
    const implementation = implementationPaths.find(item => item.sourcePath === sidecar)?.path ?? sidecar
    const relative = FS.relativePath(FS.dirname(modulePath), implementation).replace(/\.tsx?$/, '')
    lines.push(`import * as ${name} from ${JSON.stringify(relative.startsWith('.') ? relative : `./${relative}`)}`)
  }
  lines.push('')
  for (const declaration of caseSets) {
    sourceComment(declaration.$cstNode?.range)
    lines.push(caseSetTypeDeclaration(declaration))
    mapLine(declaration.$cstNode?.range)
  }
  if (caseSets.length > 0) {
    lines.push('')
  }
  for (const [index, contract] of contracts.entries()) {
    const typeName = contractTypeName(contracts, index)
    const sidecar = imports.get(contract.path)
    Assert.defined(sidecar, 'bridge sidecar import is planned')
    sourceComment(contract.sourceRange)
    lines.push(`export type ${typeName} = ${contract.type}`)
    mapLine(contract.sourceRange)
    lines.push(`${sidecar}.${contract.exportName} satisfies ${typeName}`)
    mapLine(contract.sourceRange)
    if (contract.arity !== undefined) {
      lines.push(
        `void (null as unknown as ${contract.arity} satisfies Parameters<typeof ${sidecar}.${contract.exportName}>['length'])`,
      )
      mapLine(contract.sourceRange)
    }
    if (contract.result !== undefined) {
      lines.push(
        `void (null as unknown as ReturnType<typeof ${sidecar}.${contract.exportName}> satisfies ${contract.result})`,
      )
      mapLine(contract.sourceRange)
    }
    lines.push('')
  }
  for (const type of configurationTypes) {
    sourceComment(type.sourceRange)
    for (const line of type.code.split('\n')) {
      lines.push(line)
      mapLine(type.sourceRange)
    }
    lines.push('')
  }
  return { code: `${lines.join('\n').trimEnd()}\n`, sourceMappings }
}

function caseSetTypeDeclaration(declaration: AST.TypeDeclaration): string {
  const cases = AST.caseSetCasesOf(declaration).map(item => JSON.stringify(AST.caseSetCaseName(item)))
  return `export declare const ${declaration.name}: Readonly<Record<${cases.join(' | ')}, TR.Value<any>>>`
}

/** Source metadata expands transparent aliases so their type needs no generated target module. */
function sourceConfigurationType(declaration: AST.ConfigurableDeclaration): string {
  let source = declaration
  const visited = new Set<AST.ConfigurableDeclaration>()
  while (AST.isTypeDeclaration(source) && source.aliasTarget !== undefined) {
    Assert(!visited.has(source), `acyclic configuration alias ${declaration.name}`)
    visited.add(source)
    const target = source.aliasTarget.member.ref
    Assert(
      target !== undefined && isRuntimeConfigurableDeclaration(target),
      `resolved configuration alias ${declaration.name}`,
    )
    source = target
  }
  const definition = Langium.toString(ConfigurationCompiler.ConfigurationType(source)).trimEnd()
  return definition.replace(/^export type \S+Config\b/, `export type ${declaration.name}Config`)
}

function contractTypeName(contracts: readonly BridgeContract[], index: number): string {
  const contract = contracts[index]
  Assert.defined(contract, 'bridge contract index is planned')
  return contracts.filter(candidate => candidate.exportName === contract.exportName).length === 1
    ? contract.exportName
    : `Bridge${index + 1}_${contract.exportName}`
}
