import { ASTUtils, Type } from '@ast-utils'
import { AST, type ParsedFile } from '@parser'
import { Assert, FS, Switch } from '@shared'

type BridgeContract = { arity?: string; exportName: string; path: string; result?: string; type: string }

/** BridgeMetadata is the TypeScript-facing contract generated beside each Tao boundary source. */
export const BridgeMetadata = {
  /** collect generates one module for each source that owns a TypeScript boundary. */
  collect(files: readonly ParsedFile[]): { path: string; code: string }[] {
    return files.flatMap(file => {
      const contracts = contractsOf(file.ast)
      return contracts.length === 0 ? [] : [{ path: `${file.path}.ts`, code: moduleFor(contracts, file.ast) }]
    })
  },

  /** write refreshes the generated modules without changing handwritten sidecars. */
  async write(files: readonly ParsedFile[]): Promise<string[]> {
    const modules = BridgeMetadata.collect(files)
    const expected = new Set(modules.map(module => module.path))
    for (const file of files) {
      const path = `${file.path}.ts`
      if (!expected.has(path) && await FS.isFile(path)) {
        const source = await FS.readText(path)
        if (source.startsWith('// Generated by Tao. Edit the .tao source')) {
          await FS.remove(path)
        }
      }
    }
    for (const module of modules) {
      if (!await FS.isFile(module.path) || await FS.readText(module.path) !== module.code) {
        await FS.writeText(module.path, module.code)
      }
    }
    return modules.map(module => module.path)
  },
} as const

function contractsOf(file: AST.TaoFile): BridgeContract[] {
  const contracts: BridgeContract[] = []
  for (const bridge of AST.streamAllContents(file).filter(AST.isFromExpression)) {
    const expression = bridge.expression
    const exportName = AST.isFunctionCallExpression(expression)
      ? expression.function.$refText
      : AST.isValueReference(expression)
      ? expression.target.$refText
      : undefined
    if (exportName === undefined) {
      continue
    }
    const result = bridgedResultType(bridge)
    if (result === undefined) {
      continue
    }
    const type = AST.isFunctionCallExpression(expression)
      ? `(${
        expression.argumentList?.arguments.map((argument, index) =>
          `arg${index}: ${typescriptType(Type.ofArgument(argument))}`
        ).join(', ') ?? ''
      }) => ${typescriptType(result)}`
      : typescriptType(result)
    const actionValue = result.kind === 'primitive' && result.primitive === 'action'
    contracts.push({
      ...(AST.isFunctionCallExpression(expression)
        ? { arity: String(expression.argumentList?.arguments.length ?? 0) }
        : actionValue
        ? { arity: String(result.parameters.length), result: 'void | Promise<void>' }
        : {}),
      exportName,
      path: bridge.path,
      type,
    })
  }
  for (const action of AST.streamAllContents(file).filter(AST.isActionDeclaration)) {
    if (action.foreign === undefined) {
      continue
    }
    // The compiler fills Tao defaults before invoking the handwritten implementation.
    const parameters = AST.parametersOf(action).map((parameter, index) =>
      `arg${index}: ${foreignActionParameterType(Type.ofParameter(parameter))}`
    )
    contracts.push({
      arity: String(parameters.length),
      exportName: action.name,
      path: action.foreign.path,
      result: 'void | Promise<void>',
      type: `(${parameters.join(', ')}) => void | Promise<void>`,
    })
  }
  for (const view of AST.streamAllContents(file).filter(AST.isViewDeclaration)) {
    const foreign = view.foreign
    if (foreign === undefined) {
      continue
    }
    // Tao fills defaults before passing props to the handwritten component.
    const parameters = AST.parametersOf(view).map(parameter => {
      const value = viewParameterType(Type.ofParameter(parameter))
      return `${JSON.stringify(Type.parameterName(parameter))}: ${
        parameter.mutable
          ? `{ value: ${value}; change: (next: ${value}) => void | Promise<void> }`
          : value
      }`
    })
    const slots = foreign.slots.length === 0
      ? []
      : [`Slots: { ${foreign.slots.map(slot => `${JSON.stringify(slot.name)}: any`).join('; ')} }`]
    const children = foreign.content === 'content' ? ['children?: any'] : []
    const props = [...parameters, 'Layout: any', 'Tag: any', ...slots, ...children]
    contracts.push({
      exportName: view.name,
      path: foreign.path,
      type: `(props: { ${props.join('; ')} }) => ReturnType<typeof TR.VisualNativeRoot>`,
    })
  }
  for (const declaration of file.statements.filter(AST.isConfigurableDeclaration)) {
    if (declaration.aliasTarget !== undefined) {
      continue
    }
    const primitive = AST.configurationPrimitiveOf(declaration)
    if (primitive !== 'nav' && primitive !== 'datasource') {
      continue
    }
    const implementation = AST.configurationImplementationOf(declaration)
    if (implementation?.path === undefined) {
      continue
    }
    let owner: AST.Node | undefined = implementation
    while (owner !== undefined && owner !== declaration) {
      owner = owner.$container
    }
    if (owner !== declaration) {
      continue
    }
    contracts.push({
      arity: '0',
      exportName: implementation.exportName,
      path: implementation.path,
      type: `() => ${primitive === 'nav' ? 'TR.NavKind' : 'TR.DataProvider'}`,
    })
  }
  return contracts
}

function bridgedResultType(bridge: AST.FromExpression): ASTUtils.TaoType | undefined {
  const owner = bridge.$container
  if (AST.isReturnStatement(owner)) {
    const functionOwner = AST.findOwningFunction(owner)
    return functionOwner?.returnType === undefined ? undefined : Type.ofFunctionReturn(functionOwner)
  }
  if (AST.isAliasDeclaration(owner)) {
    return owner.type === undefined ? undefined : Type.ofReference(owner.type)
  }
  if (AST.isTypeProperty(owner)) {
    return owner.type === undefined ? undefined : Type.ofReference(owner.type)
  }
  return undefined
}

function typescriptType(type: ASTUtils.TaoType, seen = new Set<AST.EntityDataDeclaration>()): string {
  return Switch.kind(type, {
    primitive: type => {
      if (type.primitive === 'action') {
        const parameters = type.parameters.map((parameter, index) =>
          `arg${index}${parameter.optional ? '?' : ''}: ${typescriptType(parameter.type, seen)}`
        )
        return `(${parameters.join(', ')}) => void | Promise<void>`
      }
      if (type.primitive === 'text' || type.primitive === 'color' || type.primitive === 'shortcut') {
        return 'string'
      }
      if (type.primitive === 'number' || type.primitive === 'time' || type.primitive === 'duration') {
        return 'number'
      }
      if (type.primitive === 'boolean') {
        return 'boolean'
      }
      if (type.primitive === 'none') {
        return 'null'
      }
      return 'unknown'
    },
    list: type => {
      const element = type.element ?? { kind: 'unresolved' }
      const rendered = typescriptType(element, seen)
      return `${element.kind === 'union' ? `(${rendered})` : rendered}[]`
    },
    union: type => type.members.map(member => typescriptType(member, seen)).join(' | '),
    entity: type => {
      if (seen.has(type.entity)) {
        return 'unknown'
      }
      seen.add(type.entity)
      const fields = Type.dataFields(type.entity).map(field =>
        `${JSON.stringify(field.name)}${field.optional ? '?' : ''}: ${typescriptType(Type.dataFieldType(field), seen)}`
      )
      seen.delete(type.entity)
      return `{ ${fields.join('; ')} }`
    },
    item: type => {
      const fields = (type.item ? Type.itemFields(type.item) : []).map(field => {
        const required = Type.itemFieldRequiresValue(field)
        const fieldType = Type.itemFieldType(field)
        const outputType = fieldType.kind === 'primitive' && fieldType.primitive === 'action'
          ? itemActionType(fieldType)
          : typescriptType(fieldType, seen)
        return `${JSON.stringify(field.name)}${required ? '' : '?'}: ${outputType}${required ? '' : ' | null'}`
      })
      return `{ ${fields.join('; ')} }`
    },
    enum: () => 'any',
    unresolved: () => 'unknown',
  })
}

/** View action parameters retain the runtime's invokable action and reactive argument wrappers. */
function viewParameterType(type: ASTUtils.TaoType): string {
  if (type.kind === 'primitive' && type.primitive === 'action') {
    return runtimeActionType(type)
  }
  return typescriptType(type)
}

function foreignActionParameterType(type: ASTUtils.TaoType): string {
  return type.kind === 'primitive' && type.primitive === 'action' ? runtimeActionType(type) : typescriptType(type)
}

function runtimeActionType(type: Extract<ASTUtils.TaoType, { kind: 'primitive'; primitive: 'action' }>): string {
  const parameters = type.parameters.map(parameter =>
    `TR.Value<${typescriptType(parameter.type)}>${parameter.optional ? '?' : ''}`
  )
  return `TR.ActionValue<[${parameters.join(', ')}]>`
}

function itemActionType(type: Extract<ASTUtils.TaoType, { kind: 'primitive'; primitive: 'action' }>): string {
  return `{ invoke(...args: [${
    type.parameters.map(parameter => `TR.Value<${typescriptType(parameter.type)}>`).join(', ')
  }]): void | Promise<void> }`
}

function moduleFor(contracts: readonly BridgeContract[], file: AST.TaoFile): string {
  const imports = new Map<string, string>()
  const lines = ['// Generated by Tao. Edit the .tao source or its handwritten TypeScript sidecar instead.', '']
  const caseSets = file.statements.filter(AST.isTypeDeclaration).filter(declaration =>
    AST.isCaseSetTypeExpression(declaration.type)
  )
  if (
    contracts.some(contract => contract.type.includes('TR.ActionValue<') || contract.type.includes('TR.Value<'))
    || caseSets.length > 0
    || contracts.some(contract => contract.type.includes('TR.NavKind') || contract.type.includes('TR.DataProvider'))
    || contracts.some(contract => contract.type.includes('TR.VisualNativeRoot'))
  ) {
    lines.push("import type TR from '@tao/runtime'")
  }
  for (const contract of contracts) {
    if (!imports.has(contract.path)) {
      imports.set(contract.path, `Sidecar${imports.size + 1}`)
    }
  }
  if (imports.size === 1) {
    const onlyPath = [...imports.keys()][0]
    Assert.defined(onlyPath, 'single bridge sidecar has one path')
    imports.set(onlyPath, 'Sidecar')
  }
  for (const [path, name] of imports) {
    lines.push(`import * as ${name} from ${JSON.stringify(path.replace(/\.tsx?$/, ''))}`)
  }
  lines.push('')
  for (const declaration of caseSets) {
    const cases = AST.caseSetCasesOf(declaration).map(item => JSON.stringify(AST.caseSetCaseName(item)))
    lines.push(`export declare const ${declaration.name}: Readonly<Record<${cases.join(' | ')}, TR.Value<any>>>`)
  }
  if (caseSets.length > 0) {
    lines.push('')
  }
  const nameCounts = new Map<string, number>()
  for (const contract of contracts) {
    nameCounts.set(contract.exportName, (nameCounts.get(contract.exportName) ?? 0) + 1)
  }
  for (const [index, contract] of contracts.entries()) {
    const typeName = nameCounts.get(contract.exportName) === 1
      ? contract.exportName
      : `Bridge${index + 1}_${contract.exportName}`
    const sidecar = imports.get(contract.path)
    Assert.defined(sidecar, 'bridge sidecar import is planned')
    lines.push(`export type ${typeName} = ${contract.type}`)
    lines.push(`${sidecar}.${contract.exportName} satisfies ${typeName}`)
    if (contract.arity !== undefined) {
      lines.push(
        `void (null as unknown as ${contract.arity} satisfies Parameters<typeof ${sidecar}.${contract.exportName}>['length'])`,
      )
    }
    if (contract.result !== undefined) {
      lines.push(
        `void (null as unknown as ReturnType<typeof ${sidecar}.${contract.exportName}> satisfies ${contract.result})`,
      )
    }
    lines.push('')
  }
  return `${lines.join('\n').trimEnd()}\n`
}
