import { type AST } from '@parser'
import { Assert, type DiagnosticRange, FS } from '@shared'
import * as ts from 'typescript'

/** The caller supplies a validated, directly owning declaration and its complete unit table. */
export type QuantityNativeOwner = Readonly<{
  owner: AST.TypeDeclaration
  units: readonly Readonly<{ name: string; scale: number }>[]
  defaultUnit: string
}>

export type QuantityNativeModuleOptions = Readonly<{
  owners: readonly QuantityNativeOwner[]
  outputPath: string
  runtimeRoot: string
  /** Names already claimed by the publication containing this leaf. */
  reservedNames?: readonly string[]
}>

/** Every consumer imports these links from the same leaf instead of recreating an owner. */
export type QuantityNativeLinkage = Readonly<{
  owner: AST.TypeDeclaration
  constructorMember: string
  typeMember: string
  valueTypeExport: string
  factoryExport: string
}>

export type QuantityNativeModuleOutput = Readonly<{
  path: string
  code: string
  namespaceExport: string
  linkageByOwner: ReadonlyMap<AST.TypeDeclaration, QuantityNativeLinkage>
  sourceMappings: readonly Readonly<{ generated: DiagnosticRange; source: DiagnosticRange }>[]
}>

/** QuantityNativeModule emits one checked factory per owner, without publishing or resolving types. */
export const QuantityNativeModule = {
  emit(options: QuantityNativeModuleOptions): QuantityNativeModuleOutput {
    Assert(options.owners.length > 0, 'quantity native module has directly owning declarations')
    const ownerSet = new Set<AST.TypeDeclaration>()
    const names = new Set([
      ...options.reservedNames ?? [],
      ...options.owners.map(entry => entry.owner.name),
    ])
    const reserve = nameAllocator(names)
    const namespaceExport = reserve('types')
    const makeFactory = reserve('__quantityMakeType')
    const factoryType = reserve('__QuantityFactory')
    const payloadType = reserve('__QuantityPayload')
    const wrap = reserve('__quantityWrap')
    const wrapperType = reserve('__QuantityValue')
    const freeze = reserve('__quantityFreeze')
    const lines = [
      '// Generated by Tao. Edit the owning Tao declaration instead.',
      `import { makeQuantityType as ${makeFactory}, type TaoQuantityFactory as ${factoryType}, type TaoQuantityPayload as ${payloadType} } from ${
        JSON.stringify(runtimeImport(options, 'TR-quantity-values'))
      }`,
      `import { reactiveValue as ${wrap}, type TaoRuntimeValue as ${wrapperType} } from ${
        JSON.stringify(runtimeImport(options, 'TR-reactive-values'))
      }`,
      `const ${freeze} = Object.freeze`,
      '',
    ]
    const sourceMappings: Array<{ generated: DiagnosticRange; source: DiagnosticRange }> = []
    const append = (line: string, source: DiagnosticRange): void => {
      sourceMappings.push({
        generated: {
          start: { line: lines.length, character: 0 },
          end: { line: lines.length, character: line.length },
        },
        source,
      })
      lines.push(line)
    }
    // Namespace assignment uses ordinary properties, so never emit its prototype setter as a member.
    const memberName = nameAllocator(new Set(['__proto__', 'eval', 'arguments']))
    const planned = options.owners.map((entry, index) => {
      Assert(!ownerSet.has(entry.owner), 'quantity native module emits each owner once')
      ownerSet.add(entry.owner)
      const source = entry.owner.$cstNode?.range
      Assert.defined(source, 'quantity native owner has a source range')
      const stem = `__q${index}`
      const symbol = reserve(`${stem}Owner`)
      const units = reserve(`${stem}Units`)
      const unit = reserve(`${stem}Unit`)
      const payload = reserve(`${stem}Payload`)
      const value = reserve(`${stem}Value`)
      const factory = reserve(`${stem}Factory`)
      const checked = reserve(`${stem}Checked`)
      const valueTypeExport = reserve(`${stem}ValueExport`)
      const factoryExport = reserve(`${stem}FactoryExport`)
      const scanner = ts.createScanner(ts.ScriptTarget.Latest, false)
      scanner.setText(entry.owner.name)
      const constructorMember = memberName(
        scanner.scan() === ts.SyntaxKind.Identifier ? entry.owner.name : `${entry.owner.name}_`,
      )
      const linkage: QuantityNativeLinkage = {
        owner: entry.owner,
        constructorMember,
        typeMember: constructorMember,
        valueTypeExport,
        factoryExport,
      }
      append(`declare const ${symbol}: unique symbol`, source)
      append(
        `type ${units} = Readonly<{ ${
          entry.units.map(row => `${JSON.stringify(row.name)}: ${row.scale}`).join('; ')
        } }>`,
        source,
      )
      append(`type ${unit} = keyof ${units}`, source)
      append(
        `type ${payload} = ${payloadType}<${
          JSON.stringify(entry.owner.name)
        }, ${unit}> & { readonly [${symbol}]: true }`,
        source,
      )
      append(`type ${value} = ${wrapperType}<${payload}>`, source)
      append(
        `type ${factory} = Omit<${factoryType}<${
          JSON.stringify(entry.owner.name)
        }, ${units}>, 'fromJSValue' | 'fromUnit' | 'inUnit' | 'read'> & Readonly<{`,
        source,
      )
      append(`  fromJSValue(input: unknown): ${value}`, source)
      append(`  fromUnit(input: unknown, unit: ${unit}): ${value}`, source)
      append(`  inUnit(value: ${value}, unit: ${unit}): ${value}`, source)
      append(`  read(value: ${value}): Readonly<{ canonical: number; unit: ${unit} }>`, source)
      append('}>', source)
      append(`const ${checked}: ${factory} = ${makeFactory}({`, source)
      append(`  domain: ${JSON.stringify(entry.owner.name)},`, source)
      append(
        `  units: { ${entry.units.map(row => `[${JSON.stringify(row.name)}]: ${row.scale}`).join(', ')} },`,
        source,
      )
      append(`  defaultUnit: ${JSON.stringify(entry.defaultUnit)},`, source)
      // The single cast brands checked payloads only; it does not retain permissive base overloads.
      append(`}, ${wrap}) as ${factory}`, source)
      append(`export type ${valueTypeExport} = ${value}`, source)
      append(`export { ${checked} as ${factoryExport} }`, source)
      lines.push('')
      return { entry, linkage, value, checked, source }
    })
    lines.push(`export namespace ${namespaceExport} {`)
    for (const { entry, linkage, value, checked, source } of planned) {
      append(`  export type ${linkage.typeMember} = ${value}`, source)
      append(`  export const ${linkage.constructorMember} = ${freeze}({`, source)
      for (const row of entry.units) {
        append(
          `    [${JSON.stringify(row.name)}]: (input: unknown): ${value} => ${checked}.fromUnit(input, ${
            JSON.stringify(row.name)
          }),`,
          source,
        )
      }
      append('  })', source)
    }
    lines.push('}')
    return {
      path: options.outputPath,
      code: `${lines.join('\n')}\n`,
      namespaceExport,
      linkageByOwner: new Map(planned.map(({ linkage }) => [linkage.owner, linkage])),
      sourceMappings,
    }
  },
} as const

function nameAllocator(names: Set<string>): (base: string) => string {
  return base => {
    let name = base
    for (let suffix = 1; names.has(name); suffix++) {
      name = `${base}_${suffix}`
    }
    names.add(name)
    return name
  }
}

function runtimeImport(options: QuantityNativeModuleOptions, module: string): string {
  const path = FS.resolvePath(`TaoRuntime-src/${module}.ts`, options.runtimeRoot)
  const relative = FS.relativePath(FS.dirname(FS.resolvePath(options.outputPath)), path).replace(/\.ts$/, '')
  return relative.startsWith('./') || relative.startsWith('../') ? relative : `./${relative}`
}
