import { type AST } from '@parser'
import { Assert, type DiagnosticRange, FS } from '@shared'
import * as ts from 'typescript'

/** The caller supplies a validated, directly owning declaration and its complete unit table. */
export type QuantityNativeOwner = Readonly<{
  owner: AST.TypeDeclaration
  units: readonly Readonly<{ name: string; scale: number }>[]
  defaultUnit: string
}>

export type QuantityNativeModuleOptions = Readonly<{
  owners: readonly QuantityNativeOwner[]
  outputPath: string
  runtimeRoot: string | Readonly<{ modulePrefix: string }>
  /** Names already claimed by the publication containing this leaf. */
  reservedNames?: readonly string[]
  /** All local quantity declarations, including aliases that only reserve surface names. */
  surfaceDeclarations?: readonly AST.TypeDeclaration[]
  /** Authenticated parent factories available to this leaf, keyed by concrete child owner. */
  parentsByOwner?: ReadonlyMap<AST.TypeDeclaration, QuantityNativeParentLink>
}>

export type QuantityNativeParentLink = Readonly<{
  owner: AST.TypeDeclaration
  path: string
  factoryExport: string
}>

/** Local publication names keyed by authored declaration identity, without resolving owners. */
export type QuantityNativeSurface = Readonly<{
  namespaceExport: string
  byDeclaration: ReadonlyMap<
    AST.TypeDeclaration,
    Readonly<{
      constructorMember: string
      typeMember: string
      valueTypeExport: string
      factoryExport: string
      factoryLocal: string
      constructorImport: string
      parent?: AST.TypeDeclaration
    }>
  >
}>

/** Every consumer imports these links from the same leaf instead of recreating an owner. */
export type QuantityNativeLinkage = Readonly<{
  owner: AST.TypeDeclaration
  constructorMember: string
  typeMember: string
  valueTypeExport: string
  factoryExport: string
}>

export type QuantityNativeModuleOutput = Readonly<{
  path: string
  code: string
  namespaceExport: string
  linkageByOwner: ReadonlyMap<AST.TypeDeclaration, QuantityNativeLinkage>
  sourceMappings: readonly Readonly<{ generated: DiagnosticRange; source: DiagnosticRange }>[]
}>

/** QuantityNativeModule emits one checked factory per owner, without publishing or resolving types. */
export const QuantityNativeModule = {
  planSurface(
    options: Readonly<{
      declarations: readonly AST.TypeDeclaration[]
      parentsByDeclaration?: ReadonlyMap<AST.TypeDeclaration, AST.TypeDeclaration>
      reservedNames?: readonly string[]
    }>,
  ): QuantityNativeSurface {
    const { namespaceExport, byDeclaration } = planNames(options)
    const plannedByDeclaration = new Map(byDeclaration)
    for (const [declaration, parent] of options.parentsByDeclaration ?? []) {
      const surface = plannedByDeclaration.get(declaration)
      Assert.defined(surface, 'quantity parent metadata belongs to a planned declaration')
      plannedByDeclaration.set(declaration, { ...surface, parent })
    }
    return { namespaceExport, byDeclaration: plannedByDeclaration }
  },

  emit(options: QuantityNativeModuleOptions): QuantityNativeModuleOutput {
    Assert(options.owners.length > 0, 'quantity native module has directly owning declarations')
    const ownerSet = new Set<AST.TypeDeclaration>()
    const plan = planNames({
      declarations: options.surfaceDeclarations ?? options.owners.map(entry => entry.owner),
      reservedNames: options.reservedNames,
    })
    const { namespaceExport, makeFactory, factoryType, payloadType, wrap, wrapperType, freeze, withFactory } = plan
    const parentsByOwner = options.parentsByOwner ?? new Map()
    const parentBindings = new Map<AST.TypeDeclaration, Readonly<{ local: string; link: QuantityNativeParentLink }>>()
    const parentImports: string[] = []
    for (const entry of options.owners) {
      const link = parentsByOwner.get(entry.owner)
      if (link === undefined) {
        continue
      }
      const localParent = link.path === options.outputPath
        ? plan.byDeclaration.get(link.owner)?.factoryLocal
        : undefined
      Assert(
        localParent !== undefined || link.path !== options.outputPath,
        'same-leaf quantity parent is included in the planned owner surface',
      )
      const local = localParent ?? plan.reserve('__quantityParentFactory')
      parentBindings.set(entry.owner, { local, link })
      if (link.path !== options.outputPath) {
        parentImports.push(
          `import { ${link.factoryExport} as ${local} } from ${
            JSON.stringify(relativeModulePath(options.outputPath, link.path))
          }`,
        )
      }
    }
    const lines = [
      '// Generated by Tao. Edit the owning Tao declaration instead.',
      `import { makeQuantityType as ${makeFactory}, type TaoQuantityFactory as ${factoryType}, type TaoQuantityPayload as ${payloadType} } from ${
        JSON.stringify(runtimeImport(options, 'TR-quantity-values'))
      }`,
      `import { reactiveValue as ${wrap}, type TaoRuntimeValue as ${wrapperType} } from ${
        JSON.stringify(runtimeImport(options, 'TR-reactive-values'))
      }`,
      ...parentImports,
      `const ${freeze} = Object.freeze`,
      `const ${withFactory} = <Constructors extends object, Factory>(constructors: Constructors, factory: Factory): Constructors & Readonly<{ Factory: Factory }> =>`,
      `  Object.defineProperty(constructors, 'Factory', { value: factory }) as Constructors & Readonly<{ Factory: Factory }>`,
      '',
    ]
    const sourceMappings: Array<{ generated: DiagnosticRange; source: DiagnosticRange }> = []
    const append = (line: string, source: DiagnosticRange): void => {
      sourceMappings.push({
        generated: {
          start: { line: lines.length, character: 0 },
          end: { line: lines.length, character: line.length },
        },
        source,
      })
      lines.push(line)
    }
    const planned = orderByParent(options.owners, parentsByOwner).map(entry => {
      Assert(!ownerSet.has(entry.owner), 'quantity native module emits each owner once')
      ownerSet.add(entry.owner)
      const source = entry.owner.$cstNode?.range
      Assert.defined(source, 'quantity native owner has a source range')
      const allocated = plan.internalsByDeclaration.get(entry.owner)
      const surface = plan.byDeclaration.get(entry.owner)
      Assert.defined(allocated, 'quantity native owner belongs to its local surface')
      Assert.defined(surface, 'quantity native owner has allocated surface names')
      const { symbol, units, unit, payload, value, factory } = allocated
      const { factoryLocal: checked, valueTypeExport, factoryExport, constructorMember } = surface
      const parentBinding = parentBindings.get(entry.owner)
      const linkage: QuantityNativeLinkage = {
        owner: entry.owner,
        constructorMember,
        typeMember: constructorMember,
        valueTypeExport,
        factoryExport,
      }
      append(`declare const ${symbol}: unique symbol`, source)
      if (parentBinding === undefined) {
        append(
          `type ${units} = Readonly<{ ${
            entry.units.map(row => `${JSON.stringify(row.name)}: ${row.scale}`).join('; ')
          } }>`,
          source,
        )
      } else {
        append(
          `type ${units} = typeof ${parentBinding.local}.definition.units`,
          source,
        )
      }
      append(`type ${unit} = keyof ${units}`, source)
      const roleProof = parentBinding === undefined
        ? `{ readonly [${symbol}]: true }`
        : `((${parentRoleProof(payloadType, parentBinding.local)}) & { readonly [${symbol}]: true })`
      append(
        `type ${payload} = ${payloadType}<${JSON.stringify(entry.owner.name)}, ${unit}, ${roleProof}>`,
        source,
      )
      append(`type ${value} = ${wrapperType}<${payload}>`, source)
      append(
        `type ${factory} = Omit<${factoryType}<${
          JSON.stringify(entry.owner.name)
        }, ${units}, ${roleProof}>, 'fromJSValue' | 'fromUnit' | 'inUnit' | 'read'> & Readonly<{`,
        source,
      )
      append(`  fromJSValue(input: unknown): ${value}`, source)
      append(`  fromUnit(input: unknown, unit: ${unit}): ${value}`, source)
      append(`  inUnit(value: ${value}, unit: ${unit}): ${value}`, source)
      append(`  read(value: ${value}): Readonly<{ canonical: number; unit: ${unit} }>`, source)
      append('}>', source)
      if (parentBinding === undefined) {
        append(
          `const ${checked}: ${factory} = ${makeFactory}<${
            JSON.stringify(entry.owner.name)
          }, ${units}, ${roleProof}>({`,
          source,
        )
        append(`  domain: ${JSON.stringify(entry.owner.name)},`, source)
        append(
          `  units: { ${entry.units.map(row => `[${JSON.stringify(row.name)}]: ${row.scale}`).join(', ')} },`,
          source,
        )
        append(`  defaultUnit: ${JSON.stringify(entry.defaultUnit)},`, source)
        // The single cast narrows the public factory surface without retaining permissive base overloads.
        append(`}, ${wrap}) as ${factory}`, source)
      } else {
        append(
          `const ${checked}: ${factory} = ${parentBinding.local}.derive<${
            JSON.stringify(entry.owner.name)
          }, { readonly [${symbol}]: true }>({ domain: ${JSON.stringify(entry.owner.name)} })`,
          source,
        )
      }
      append(`export type ${valueTypeExport} = ${value}`, source)
      append(`export { ${checked} as ${factoryExport} }`, source)
      lines.push('')
      return { entry, linkage, value, checked, source }
    })
    lines.push(`export namespace ${namespaceExport} {`)
    for (const { entry, linkage, value, checked, source } of planned) {
      append(`  export type ${linkage.typeMember} = ${value}`, source)
      // The capitalized bridge-only member cannot collide with an authored lowercase unit.
      // Keep it nonenumerable so native code can still enumerate just the unit constructors.
      append(`  export const ${linkage.constructorMember} = ${freeze}(${withFactory}({`, source)
      for (const row of entry.units) {
        append(
          `    [${JSON.stringify(row.name)}]: (input: unknown): ${value} => ${checked}.fromUnit(input, ${
            JSON.stringify(row.name)
          }),`,
          source,
        )
      }
      append(`  }, ${checked}))`, source)
    }
    lines.push('}')
    return {
      path: options.outputPath,
      code: `${lines.join('\n')}\n`,
      namespaceExport,
      linkageByOwner: new Map(planned.map(({ linkage }) => [linkage.owner, linkage])),
      sourceMappings,
    }
  },
} as const

function planNames(
  options: Readonly<{
    declarations: readonly AST.TypeDeclaration[]
    reservedNames?: readonly string[]
  }>,
) {
  const reserve = nameAllocator(
    new Set([
      ...options.reservedNames ?? [],
      ...options.declarations.map(declaration => declaration.name),
    ]),
  )
  const namespaceExport = reserve('types')
  const makeFactory = reserve('__quantityMakeType')
  const factoryType = reserve('__QuantityFactory')
  const payloadType = reserve('__QuantityPayload')
  const wrap = reserve('__quantityWrap')
  const wrapperType = reserve('__QuantityValue')
  const freeze = reserve('__quantityFreeze')
  // Namespace assignment uses ordinary properties, so never emit its prototype setter as a member.
  const memberName = nameAllocator(new Set(['__proto__', 'eval', 'arguments']))
  const internalsByDeclaration = new Map<
    AST.TypeDeclaration,
    Readonly<{
      symbol: string
      units: string
      unit: string
      payload: string
      value: string
      factory: string
    }>
  >()
  const allocated = options.declarations.map((declaration, index) => {
    Assert(!internalsByDeclaration.has(declaration), 'quantity native surface plans each declaration once')
    const stem = `__q${index}`
    const symbol = reserve(`${stem}Owner`)
    const units = reserve(`${stem}Units`)
    const unit = reserve(`${stem}Unit`)
    const payload = reserve(`${stem}Payload`)
    const value = reserve(`${stem}Value`)
    const factory = reserve(`${stem}Factory`)
    const factoryLocal = reserve(`${stem}Checked`)
    const valueTypeExport = reserve(`${stem}ValueExport`)
    const factoryExport = reserve(`${stem}FactoryExport`)
    const scanner = ts.createScanner(ts.ScriptTarget.Latest, false)
    scanner.setText(declaration.name)
    const constructorMember = memberName(
      scanner.scan() === ts.SyntaxKind.Identifier ? declaration.name : `${declaration.name}_`,
    )
    internalsByDeclaration.set(declaration, { symbol, units, unit, payload, value, factory })
    return {
      declaration,
      stem,
      constructorMember,
      typeMember: constructorMember,
      valueTypeExport,
      factoryExport,
      factoryLocal,
    }
  })
  // Imports are additional metadata; allocate them only after the established direct-export ABI.
  const byDeclaration: QuantityNativeSurface['byDeclaration'] = new Map(
    allocated.map(({ declaration, stem, ...surface }) => [
      declaration,
      { ...surface, constructorImport: reserve(`${stem}ConstructorImport`) },
    ]),
  )
  const withFactory = reserve('__quantityWithFactory')
  return {
    namespaceExport,
    byDeclaration,
    internalsByDeclaration,
    makeFactory,
    factoryType,
    payloadType,
    wrap,
    wrapperType,
    freeze,
    withFactory,
    reserve,
  }
}

function orderByParent(
  owners: readonly QuantityNativeOwner[],
  parents: ReadonlyMap<AST.TypeDeclaration, QuantityNativeParentLink>,
): QuantityNativeOwner[] {
  const byOwner = new Map(owners.map(entry => [entry.owner, entry]))
  const visiting = new Set<AST.TypeDeclaration>()
  const visited = new Set<AST.TypeDeclaration>()
  const ordered: QuantityNativeOwner[] = []
  const visit = (owner: AST.TypeDeclaration): void => {
    if (visited.has(owner)) {
      return
    }
    Assert(!visiting.has(owner), 'quantity parent ancestry is acyclic')
    visiting.add(owner)
    const parent = parents.get(owner)
    if (parent !== undefined && byOwner.has(parent.owner)) {
      visit(parent.owner)
    }
    visiting.delete(owner)
    visited.add(owner)
    const entry = byOwner.get(owner)
    if (entry !== undefined) {
      ordered.push(entry)
    }
  }
  for (const entry of owners) {
    visit(entry.owner)
  }
  return ordered
}

function parentRoleProof(payloadType: string, local: string): string {
  return `ReturnType<typeof ${local}.fromJSValue>['jsValue'] extends ${payloadType}<string, string, infer ParentProof> ? ParentProof : never`
}

function relativeModulePath(from: string, to: string): string {
  const relative = FS.relativePath(FS.dirname(FS.resolvePath(from)), FS.resolvePath(to)).replace(/\.ts$/, '')
  return relative.startsWith('.') ? relative : `./${relative}`
}

function nameAllocator(names: Set<string>): (base: string) => string {
  return base => {
    let name = base
    for (let suffix = 1; names.has(name); suffix++) {
      name = `${base}_${suffix}`
    }
    names.add(name)
    return name
  }
}

function runtimeImport(options: QuantityNativeModuleOptions, module: string): string {
  if (typeof options.runtimeRoot !== 'string') {
    return `${options.runtimeRoot.modulePrefix}/${module}`
  }
  const path = FS.resolvePath(`TaoRuntime-src/${module}.ts`, options.runtimeRoot)
  const relative = FS.relativePath(FS.dirname(FS.resolvePath(options.outputPath)), path).replace(/\.ts$/, '')
  return relative.startsWith('./') || relative.startsWith('../') ? relative : `./${relative}`
}
