import { FS } from '@shared'
import { Describe, Expect, Test, withTaoFiles } from '@shared/test'
import { ProjectTooling } from '../project-tooling-src/ProjectToolingService'
import { semanticResult, warmReceipt } from './ProjectRefreshReceiptTestSupport'

Describe('watched project refresh receipt resolution', () => {
  Test('replays internal sidecar resolution and recovers a newly missing relative target', async () => {
    await withTaoFiles('tao-refresh-receipt-sidecars-', {
      'Main.tao': 'function CountWords(Value text) returns number { return CountWords(Value) from ./Words.ts }\n',
      'Words.ts': "import { count } from './Helper'\nexport const CountWords = count\n",
      'Helper.js': 'export function count(value) { return value.length }\n',
      'tsconfig.json':
        '{"extends":"./.tao/cache/typescript/tsconfig.json","compilerOptions":{"noImplicitAny":false}}\n',
    }, async (paths, root) => {
      const watch = await ProjectTooling.watch(root, {})
      try {
        const first = await warmReceipt(watch)
        await FS.writeText(
          FS.resolvePath('Helper.ts', root),
          'export function count(value: string): string { return value }\n',
        )
        const higherPriority = await watch.requestRefresh()
        Expect(higherPriority.revision).toBeGreaterThan(first.revision)
        Expect(higherPriority.status).toBe('stale')
        Expect(higherPriority.diagnostics.some(diagnostic => diagnostic.code === 'TS2344')).toBe(true)
        Expect(semanticResult(higherPriority)).toEqual(semanticResult(await watch.requestRefresh({ force: true })))
        await FS.remove(FS.resolvePath('Helper.ts', root))
        await FS.remove(paths['Helper.js'])
        const missing = await watch.requestRefresh()
        Expect(missing.status).toBe('stale')
        Expect(missing.diagnostics.some(diagnostic => diagnostic.message.includes('could not be resolved'))).toBe(true)
        await FS.writeText(
          FS.resolvePath('Helper.ts', root),
          'export function count(value: string): number { return value.length }\n',
        )
        const repaired = await watch.requestRefresh()
        Expect(repaired.status).toBe('fresh')
        Expect(repaired.revision).toBeGreaterThan(missing.revision)
        Expect((await warmReceipt(watch)).status).toBe('fresh')
      } finally {
        await watch.dispose()
      }
    }, { location: 'host' })
  })

  Test('audits selected dependency source and repairs its copied snapshot independently of contracts', async () => {
    await withTaoFiles('tao-refresh-receipt-dependency-', {
      'Library/.tao/.gitkeep': '',
      'Library/Package.tao': 'package { name "Widget Package" version 2.0.0 includes @widgets }\n',
      'Library/@widgets/Widget.tao':
        'public function CountWords(Value text) returns number { return CountWords(Value) from ./Words.ts }\n',
      'Library/@widgets/Words.ts':
        "import { suffix } from './Helper'\nexport function CountWords(value: string): number { return (value + suffix).length }\n",
      'Library/@widgets/Helper.ts': "export const suffix = '!'\n",
      'Consumer/.tao/.gitkeep': '',
      'Consumer/Main.tao':
        'use CountWords from @parts\npackage { version 0.1.0 requires "Widget Package" from ../Library version ^2.0.0 { @widgets as @parts } }\n',
    }, async (paths, fixture) => {
      const root = FS.resolvePath('Consumer', fixture)
      const watch = await ProjectTooling.watch(root, {})
      try {
        let warm = await watch.requestRefresh()
        Expect(warm.dependencyRoots).toEqual([FS.resolvePath('Library', fixture)])
        const snapshots: string[] = []
        for await (const path of FS.walk(FS.resolvePath('.tao-ts/.dependencies', root), { includeHidden: true })) {
          if (path.endsWith('/Helper.ts')) {
            snapshots.push(path)
          }
        }
        Expect(snapshots).toHaveLength(1)
        const snapshot = snapshots[0]!
        const originalSnapshot = await FS.readText(snapshot)
        await FS.writeText(
          snapshot,
          '// Generated by Tao from a dependency source.\nexport const suffix = "corrupted"\n',
        )
        const repaired = await watch.requestRefresh()
        Expect(repaired.revision).toBeGreaterThan(warm.revision)
        Expect(repaired.changedOutputPaths).toContain(snapshot)
        Expect(await FS.readText(snapshot)).toBe(originalSnapshot)
        warm = await watch.requestRefresh()
        await FS.writeText(paths['Library/@widgets/Helper.ts'], 'export const suffix = "changed"\n')
        const changed = await watch.requestRefresh()
        Expect(changed.revision).toBeGreaterThan(warm.revision)
        Expect(changed.status).toBe('fresh')
        Expect(changed.changedOutputPaths).toContain(snapshot)
        Expect(await FS.readText(snapshot)).toContain('"changed"')
        Expect(semanticResult(changed)).toEqual(semanticResult(await watch.requestRefresh({ force: true })))
      } finally {
        await watch.dispose()
      }
    }, { location: 'host', verbatim: true })
  })

  Test('keeps external sidecars on the authoritative cold resolution path', async () => {
    await withTaoFiles('tao-refresh-receipt-external-', {
      'Project/.tao/.gitkeep': '',
      'Project/Main.tao': 'view Widget() from ../Host/Widget.tsx\n',
      'Host/Widget.tsx': 'export function Widget() { return null }\n',
    }, async (_paths, fixture) => {
      const root = FS.resolvePath('Project', fixture)
      const watch = await ProjectTooling.watch(root, {})
      try {
        const first = await watch.requestRefresh()
        const second = await watch.requestRefresh()
        Expect(first.status).toBe('fresh')
        Expect(second.status).toBe('fresh')
        Expect(second.revision).toBeGreaterThan(first.revision)
        Expect(second.externalSidecarInputPaths).toEqual([FS.resolvePath('Host/Widget.tsx', fixture)])
        Expect(semanticResult(second)).toEqual(semanticResult(await watch.requestRefresh({ force: true })))
      } finally {
        await watch.dispose()
      }
    }, { location: 'host', verbatim: true })
  })
})
