import { FS } from '@shared'
import { Describe, Expect, mkTestDir, Test } from '@shared/test'
import { publishProjectOutputs, snapshotContent } from '../project-tooling-src/ProjectOutputPublisher'

Describe('project output publication', () => {
  Test('writes only changed generated content and retains last good output until its source is deleted', async () => {
    const root = await mkTestDir('tao-project-output-')
    try {
      await FS.mkdir(FS.resolvePath('.tao', root))
      const sourcePath = FS.resolvePath('View.tao', root)
      const outputPath = FS.resolvePath('.tao-ts/View.tao.ts', root)
      const handwrittenPath = FS.resolvePath('.tao-ts/Hand.ts', root)
      await FS.writeText(sourcePath, 'view View() { }\n')
      await FS.writeText(handwrittenPath, 'export const Hand = true\n')
      const output = {
        path: outputPath,
        sourcePath,
        content: '// Generated by Tao. Edit View.tao instead.\nexport type View = {}\n',
        kind: 'contract' as const,
        sourceMappings: [],
      }
      const first = await publishProjectOutputs(root, [output])
      Expect(first.contractPaths).toEqual([outputPath])
      Expect(first.changedOutputPaths).toContain(outputPath)

      const unchanged = await publishProjectOutputs(root, [output])
      Expect(unchanged.changedOutputPaths).toEqual([])
      const stale = await publishProjectOutputs(root, undefined)
      Expect(stale.contractPaths).toEqual([outputPath])
      Expect(stale.changedOutputPaths).toEqual([])

      await FS.remove(sourcePath)
      const deleted = await publishProjectOutputs(root, undefined)
      Expect(deleted.contractPaths).toEqual([])
      Expect(deleted.changedOutputPaths).toContain(outputPath)
      Expect(await FS.exists(outputPath)).toBe(false)
      Expect(await FS.readText(handwrittenPath)).toBe('export const Hand = true\n')
    } finally {
      await FS.remove(root)
    }
  })

  Test('refuses to overwrite an unowned handwritten output path', async () => {
    const root = await mkTestDir('tao-project-output-owned-')
    try {
      const sourcePath = FS.resolvePath('View.tao', root)
      const path = FS.resolvePath('.tao-ts/View.tao.ts', root)
      await FS.writeText(sourcePath, 'view View() { }\n')
      await FS.writeText(path, 'export const Handwritten = true\n')
      await Expect(publishProjectOutputs(root, [{
        path,
        sourcePath,
        content: '// Generated by Tao.\n',
        kind: 'contract',
        sourceMappings: [],
      }])).rejects.toThrow('handwritten file')
      Expect(await FS.readText(path)).toBe('export const Handwritten = true\n')
    } finally {
      await FS.remove(root)
    }
  })

  Test('copies JSON bytes without a comment and identifies it by its manifest hash', async () => {
    const root = await mkTestDir('tao-project-json-output-')
    try {
      const sourcePath = FS.resolvePath('data.json', root)
      const path = FS.resolvePath('.tao-ts/.dependencies/abc/data.json', root)
      await FS.writeText(sourcePath, '{"name":"cards"}\n')
      const content = snapshotContent(sourcePath, await FS.readText(sourcePath))
      Expect(content).toBe('{"name":"cards"}\n')
      await publishProjectOutputs(root, [{ path, sourcePath, content, kind: 'snapshot', sourceMappings: [] }])
      await FS.remove(sourcePath)
      const afterDelete = await publishProjectOutputs(root, undefined)
      Expect(afterDelete.changedOutputPaths).toContain(path)
      Expect(await FS.exists(path)).toBe(false)
    } finally {
      await FS.remove(root)
    }
  })
})
