import { Workspace } from '@compiler/workspace'
import { FS } from '@shared'
import { Describe, Expect, Test, withTaoFiles } from '@shared/test'
import type { ProjectToolingWatch } from '../project-tooling-src/ProjectTooling'
import { ProjectTooling } from '../project-tooling-src/ProjectToolingService'
import {
  registerMissingContractMutationTest,
  registerReceiptMutationTest,
  semanticResult,
  validationSlot,
  warmReceipt,
} from './ProjectRefreshReceiptTestSupport'

Describe('watched project refresh receipt reuse', () => {
  Test(
    'skips the complete validated graph for matching saves, preserves cold parity, and releases on disposal',
    async () => {
      await withTaoFiles('tao-refresh-receipt-reuse-', {
        'Main.tao': 'use Stack from @tao/ui\ntype Answer is one of One, Two\n',
      }, async (_paths, root) => {
        const original = Workspace.prototype.validateFiles
        let validations = 0
        const restore = validationSlot.install(async function(this: Workspace, paths) {
          if (paths.some(path => FS.pathIsWithin(path, root))) {
            validations += 1
          }
          return await original.call(this, paths)
        })
        const watches: ProjectToolingWatch[] = []
        try {
          const watch = await ProjectTooling.watch(root, {})
          watches.push(watch)
          const warm = await warmReceipt(watch)
          Expect(warm.status).toBe('fresh')
          Expect(warm.diagnostics.some(diagnostic => diagnostic.severity === 'warning')).toBe(true)
          Expect(warm.diagnostics.every(diagnostic => diagnostic.severity !== 'error')).toBe(true)
          Expect(warm.contractPaths).toEqual([FS.resolvePath('.tao-ts/Main.tao.ts', root)])
          const count = validations
          Expect(count).toBeGreaterThan(0)
          for (let index = 0; index < 3; index += 1) {
            const reused = await watch.requestRefresh()
            Expect(reused.revision).toBe(warm.revision)
            Expect(reused.changedOutputPaths).toEqual([])
            Expect(semanticResult(reused)).toEqual(semanticResult(warm))
          }
          Expect(validations).toBe(count)
          const forced = await watch.requestRefresh({ force: true })
          Expect(forced.revision).toBeGreaterThan(warm.revision)
          Expect(validations).toBeGreaterThan(count)
          Expect(semanticResult(forced)).toEqual(semanticResult(warm))
          Expect(semanticResult(await ProjectTooling.refresh(root, {}))).toEqual(semanticResult(warm))

          await watch.dispose()
          await watch.dispose()
          await Expect(watch.requestRefresh()).rejects.toThrow('disposed')
          const beforeReopen = validations
          const reopened = await ProjectTooling.watch(root, {})
          watches.push(reopened)
          Expect(reopened.lastResult.revision).toBeGreaterThan(forced.revision)
          Expect(validations).toBeGreaterThan(beforeReopen)
        } finally {
          await Promise.all(watches.map(watch => watch.dispose()))
          restore()
        }
      }, { location: 'host' })
    },
  )
  const fixture = {
    'Main.tao': 'type Answer is one of One, Two\n',
    'Nested/Value.ts': 'export const value = 1\n',
  }
  registerReceiptMutationTest(
    'repairs an individually corrupted generated contract',
    fixture,
    (_paths, root) => FS.resolvePath('.tao-ts/Main.tao.ts', root),
    '// Generated by Tao.\nexport const corrupted: number = "wrong"\n',
    'fresh',
  )
  registerReceiptMutationTest(
    'repairs an individually corrupted generated tsconfig',
    fixture,
    (_paths, root) => FS.resolvePath('.tao/cache/typescript/tsconfig.json', root),
    '{}\n',
    'fresh',
  )
  registerReceiptMutationTest(
    'repairs an individually corrupted outputs manifest',
    fixture,
    (_paths, root) => FS.resolvePath('.tao/cache/typescript/outputs.json', root),
    '{"version":1,"outputs":[]}\n',
    'fresh',
  )
  registerMissingContractMutationTest()
})
