import { FS } from '@shared'
import { Describe } from '@shared/test'
import { registerReceiptMutationTest } from './ProjectRefreshReceiptTestSupport'

Describe('watched project refresh receipt repairs', () => {
  const fixture = {
    'Main.tao': 'type Answer is one of One, Two\n',
    'Nested/Value.ts': 'export const value = 1\n',
  }
  registerReceiptMutationTest(
    'repairs an individually corrupted generated contract',
    fixture,
    (_paths, root) => FS.resolvePath('.tao-ts/Main.tao.ts', root),
    '// Generated by Tao.\nexport const corrupted: number = "wrong"\n',
    'fresh',
    true,
  )
  registerReceiptMutationTest(
    'repairs an individually corrupted generated tsconfig',
    fixture,
    (_paths, root) => FS.resolvePath('.tao/cache/typescript/tsconfig.json', root),
    '{}\n',
    'fresh',
    true,
  )
  registerReceiptMutationTest(
    'repairs an individually corrupted outputs manifest',
    fixture,
    (_paths, root) => FS.resolvePath('.tao/cache/typescript/outputs.json', root),
    '{"version":1,"outputs":[]}\n',
    'fresh',
    true,
  )
})
