import { FS } from '@shared'
import { Describe } from '@shared/test'
import { registerReceiptMutationCases } from './ProjectRefreshReceiptTestSupport'

Describe('watched project refresh receipt repairs', () => {
  registerReceiptMutationCases('repairs individually corrupted generated outputs', {
    'Main.tao': 'type Answer is one of One, Two\n',
    'Nested/Value.ts': 'export const value = 1\n',
  }, [
    {
      title: 'generated contract',
      target: (_paths, root) => FS.resolvePath('.tao-ts/Main.tao.ts', root),
      content: '// Generated by Tao.\nexport const corrupted: number = "wrong"\n',
      expectedStatus: 'fresh',
      generatedOutput: true,
    },
    {
      title: 'generated tsconfig',
      target: (_paths, root) => FS.resolvePath('.tao/cache/typescript/tsconfig.json', root),
      content: '{}\n',
      expectedStatus: 'fresh',
      generatedOutput: true,
    },
    {
      title: 'outputs manifest',
      target: (_paths, root) => FS.resolvePath('.tao/cache/typescript/outputs.json', root),
      content: '{"version":1,"outputs":[]}\n',
      expectedStatus: 'fresh',
      generatedOutput: true,
    },
  ])
})
